@extends('layouts.app')

@section('title', 'Edit Pembelian Aset')

@section('breadcrumb')
<li class="breadcrumb-item text-muted"><a href="{{ route('asset-purchases.index') }}" class="text-muted text-hover-primary">Pembelian Aset</a></li>
<li class="breadcrumb-item"><span class="bullet bg-gray-500 w-5px h-2px"></span></li>
<li class="breadcrumb-item text-muted">Edit</li>
@endsection

@section('toolbar_actions')
<a href="{{ route('asset-purchases.show', $assetPurchase) }}" class="btn btn-sm btn-light"><i class="ki-duotone ki-left fs-3"></i> Kembali</a>
@endsection

@section('content')
<div class="card card-flush">
    <div class="card-header border-0 pt-6"><div class="card-title"><h2 class="fw-bold">Edit Pembelian Aset</h2></div></div>
    <form id="assetForm" method="POST" action="{{ route('asset-purchases.update', $assetPurchase) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-body pt-0">
            @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div class="row g-5">
                <div class="col-md-6"><label class="required form-label fw-semibold">Nama Aset</label><input name="asset_name" class="form-control" value="{{ old('asset_name', $assetPurchase->asset_name) }}" required></div>
                <div class="col-md-6"><label class="form-label fw-semibold">Merk/Brand</label><input name="supplier" class="form-control" value="{{ old('supplier', $assetPurchase->supplier) }}" placeholder="Contoh: Yamaha, Honda, Bosch"></div>
                <div class="col-md-6"><label class="form-label fw-semibold">Serial Number</label><input name="serial_number" class="form-control" value="{{ old('serial_number', $assetPurchase->serial_number) }}" placeholder="Opsional"></div>
                <div class="col-md-3"><label class="form-label fw-semibold">Status Aset</label><select name="condition_status" class="form-select"><option value="bagus" @selected(old('condition_status', $assetPurchase->condition_status ?? 'bagus')==='bagus')>Bagus</option><option value="rusak" @selected(old('condition_status', $assetPurchase->condition_status)==='rusak')>Rusak</option></select></div>
                <div class="col-md-3"><label class="required form-label fw-semibold">Kategori Aset</label><select name="asset_category_id" class="form-select" required><option value="">-- Pilih --</option>@foreach($assetCategories as $category)<option value="{{ $category->id }}" @selected(old('asset_category_id', $assetPurchase->asset_category_id)==$category->id)>{{ $category->code }} - {{ $category->name }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="required form-label fw-semibold">Tanggal Pembelian</label><div class="input-group"><span class="input-group-text"><i class="ki-duotone ki-calendar fs-3"><span class="path1"></span><span class="path2"></span></i></span><input type="text" name="purchase_date" id="purchaseDate" class="form-control" placeholder="Pilih tanggal" value="{{ old('purchase_date', $assetPurchase->purchase_date?->format('Y-m-d')) }}" required></div></div>
                <div class="col-md-4"><label class="required form-label fw-semibold">Nominal Pembelian</label><div class="input-group"><span class="input-group-text">Rp</span><input type="text" id="amountDisplay" class="form-control money" value="{{ number_format((int) old('purchase_amount', $assetPurchase->purchase_amount),0,',','.') }}" required></div><input type="hidden" name="purchase_amount" id="amountValue" value="{{ old('purchase_amount', (int) $assetPurchase->purchase_amount) }}"></div>
                <div class="col-md-4"><label class="required form-label fw-semibold">Umur Manfaat</label><div class="input-group"><input type="number" min="0" name="useful_life_years" class="form-control" value="{{ old('useful_life_years', $assetPurchase->useful_life_years) }}" required><span class="input-group-text">tahun</span></div></div>
                <div class="col-md-4" id="methodCol"><label class="required form-label fw-semibold">Metode Depresiasi</label><select name="depreciation_method" id="depreciationMethod" class="form-select" required><option value="straight_line" @selected(old('depreciation_method', $assetPurchase->depreciation_method)==='straight_line')>Garis Lurus</option><option value="percentage" @selected(old('depreciation_method', $assetPurchase->depreciation_method)==='percentage')>Persen</option><option value="none" @selected(old('depreciation_method', $assetPurchase->depreciation_method)==='none')>Tanpa Depresiasi</option></select></div>
                <div class="col-md-4" id="percentCol"><label class="form-label fw-semibold">Persen Depresiasi</label><div class="input-group"><input type="number" step="0.01" min="0" max="100" name="depreciation_percentage" class="form-control" value="{{ old('depreciation_percentage', $assetPurchase->depreciation_percentage) }}"><span class="input-group-text">%</span></div></div>
                <div class="col-md-4" id="residualCol"><label class="form-label fw-semibold">Nilai Residu</label><div class="input-group"><span class="input-group-text">Rp</span><input type="text" id="residualDisplay" class="form-control money" value="{{ number_format((int) old('residual_value', $assetPurchase->residual_value),0,',','.') }}"></div><input type="hidden" name="residual_value" id="residualValue" value="{{ old('residual_value', (int) $assetPurchase->residual_value) }}"><div class="form-text">Estimasi nilai sisa aset saat umur manfaatnya berakhir.</div></div>
                <div class="col-12"><label class="required form-label fw-semibold">Bank/Cash</label><select name="bank_account_id" class="form-select bank-account-select" required><option value="">-- Pilih Bank --</option>@foreach($bankAccounts as $bank)<option value="{{ $bank->id }}" data-logo-url="{{ $bank->logo_url }}" data-logo-text="{{ $bank->logo_text }}" data-bank-name="{{ $bank->bank_name }}" data-bank-code="{{ $bank->code }}" data-bank-balance="Rp {{ number_format($bank->balance,0,',','.') }}" @selected(old('bank_account_id', $assetPurchase->bank_account_id)==$bank->id)>{{ $bank->bank_name }}</option>@endforeach</select><div class="form-text">Saat disetujui, pembelian aset tercatat sebagai uang keluar dari bank ini.</div></div>
                <div class="col-md-6"><label class="form-label fw-semibold">Foto Aset Baru</label><input type="file" name="asset_photos[]" id="assetPhotosInput" class="form-control preview-input" data-preview="assetPhotosPreview" accept=".jpg,.jpeg,.png,.webp" multiple><div class="form-text">Kosongkan jika foto lama tetap dipakai. Gambar baru akan dikompres ke WebP dan disimpan ke R2.</div></div>
                <div class="col-md-6"><label class="form-label fw-semibold">Eviden Baru</label><input type="file" name="evidence[]" id="assetEvidenceInput" class="form-control preview-input" data-preview="assetEvidencePreview" accept=".jpg,.jpeg,.png,.webp,.pdf" multiple><div class="form-text">Kosongkan jika eviden lama tetap dipakai.</div></div>
                <div class="col-md-6"><div id="assetPhotosPreview" class="d-none border rounded p-3"><div class="fw-semibold mb-3">Preview Foto Aset Baru</div><div class="row g-3 preview-list"></div></div></div>
                <div class="col-md-6"><div id="assetEvidencePreview" class="d-none border rounded p-3"><div class="fw-semibold mb-3">Preview Eviden Baru</div><div class="row g-3 preview-list"></div></div></div>
                <div class="col-12"><label class="form-label fw-semibold">Catatan</label><textarea name="notes" class="form-control" rows="3">{{ old('notes', $assetPurchase->notes) }}</textarea></div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-end"><a href="{{ route('asset-purchases.show', $assetPurchase) }}" class="btn btn-light me-3">Batal</a><button class="btn btn-primary"><i class="ki-duotone ki-send fs-3"><span class="path1"></span><span class="path2"></span></i> Update & Ajukan</button></div>
    </form>
</div>

<div class="modal fade" id="assetPreviewModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-xl"><div class="modal-content"><div class="modal-header"><h2 class="fw-bold">Preview File</h2><div class="btn btn-icon btn-sm btn-active-icon-primary" data-bs-dismiss="modal"><i class="ki-duotone ki-cross fs-1"><span class="path1"></span><span class="path2"></span></i></div></div><div class="modal-body" id="assetPreviewModalBody"></div></div></div></div>
@endsection

@push('styles')
<style>.bank-select-option{display:flex;align-items:center;gap:10px;min-width:0}.bank-select-logo{width:32px;height:32px;border:1px solid #dfe6f2;border-radius:9px;background:#fff;display:flex;align-items:center;justify-content:center;flex-shrink:0;overflow:hidden}.bank-select-logo img{max-width:26px;max-height:18px;object-fit:contain}.bank-select-logo span{font-size:10px;font-weight:800;color:#1d4ed8}.bank-select-text{min-width:0;line-height:1.25}.bank-select-text .name{font-weight:700;color:#1f2937;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bank-select-text .meta{font-size:11px;color:#7e8299;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}</style>
@endpush

@push('scripts')
<script>
function bankOptionTemplate(option){if(!option.id)return option.text;var el=option.element;var logoUrl=el.getAttribute('data-logo-url');var logoText=el.getAttribute('data-logo-text')||'BNK';var bankName=el.getAttribute('data-bank-name')||option.text;var bankCode=el.getAttribute('data-bank-code')||'';var balance=el.getAttribute('data-bank-balance')||'';var logo=logoUrl?'<img src="'+logoUrl+'" alt="'+bankName.replace(/"/g,'&quot;')+'">':'<span>'+logoText+'</span>';return $('<div class="bank-select-option"><div class="bank-select-logo">'+logo+'</div><div class="bank-select-text"><div class="name">'+bankCode+' - '+bankName+'</div><div class="meta">Saldo '+balance+'</div></div></div>');}
function normalize(v){return(v||'').toString().replace(/\D/g,'').replace(/^0+(?=\d)/,'');}function format(v){var d=normalize(v);return d?d.replace(/\B(?=(\d{3})+(?!\d))/g,'.'):'';}function bindMoney(display,value){var d=document.getElementById(display),v=document.getElementById(value);if(!d||!v)return;d.addEventListener('input',function(){var x=normalize(this.value);this.value=format(x);v.value=x||0;});}
bindMoney('amountDisplay','amountValue');bindMoney('residualDisplay','residualValue');$('#purchaseDate').flatpickr({dateFormat:'Y-m-d',allowInput:true});$('.bank-account-select').select2({width:'100%',templateResult:bankOptionTemplate,templateSelection:bankOptionTemplate,escapeMarkup:function(markup){return markup;}});
function syncDepreciation(){var method=$('#depreciationMethod').val();$('#percentCol').toggleClass('d-none',method!=='percentage');$('#residualCol').toggleClass('d-none',method==='none');if(method!=='percentage')$('[name=depreciation_percentage]').val('');if(method==='none'){$('#residualDisplay').val('0');$('#residualValue').val('0');}}$('#depreciationMethod').on('change',syncDepreciation);syncDepreciation();
var previewState={};function renderPreview(input){var box=document.getElementById(input.dataset.preview);var list=box.querySelector('.preview-list');var files=Array.from(input.files||[]);previewState[input.id]=(previewState[input.id]||[]);previewState[input.id].forEach(function(url){URL.revokeObjectURL(url);});previewState[input.id]=[];list.innerHTML='';if(!files.length){box.classList.add('d-none');return;}files.forEach(function(file){var url=URL.createObjectURL(file);previewState[input.id].push(url);var isImage=file.type.indexOf('image/')===0;var thumb=isImage?'<img src="'+url+'" class="w-100 h-100" style="object-fit:cover" alt="Preview">':'<span class="badge badge-light-primary">'+((file.name.split('.').pop()||'FILE').toUpperCase())+'</span>';var col=document.createElement('div');col.className='col-md-6';col.innerHTML='<div class="border rounded p-3 h-100"><button type="button" class="border rounded bg-light d-flex align-items-center justify-content-center w-100 mb-3 preview-open" data-url="'+url+'" data-type="'+(isImage?'image':'file')+'" style="height:120px;overflow:hidden;">'+thumb+'</button><div class="fw-semibold text-truncate" title="'+file.name+'">'+file.name+'</div></div>';list.appendChild(col);});box.classList.remove('d-none');}
document.querySelectorAll('.preview-input').forEach(function(input){input.addEventListener('change',function(){renderPreview(this);});});document.addEventListener('click',function(e){var btn=e.target.closest('.preview-open');if(!btn)return;document.getElementById('assetPreviewModalBody').innerHTML=btn.dataset.type==='image'?'<img src="'+btn.dataset.url+'" class="w-100 rounded" alt="Preview">':'<iframe src="'+btn.dataset.url+'" class="w-100 border-0 rounded" style="height:75vh;"></iframe>';new bootstrap.Modal(document.getElementById('assetPreviewModal')).show();});
</script>
@endpush
